-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" TEXT,
ADD COLUMN IF NOT EXISTS "agent_price_types" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN IF NOT EXISTS "agent_entitlements" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "max_sessions" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN IF NOT EXISTS "kpi_color" VARCHAR(16);

-- AlterTable
ALTER TABLE "refresh_tokens" ADD COLUMN IF NOT EXISTS "device_name" TEXT,
ADD COLUMN IF NOT EXISTS "ip_address" VARCHAR(64),
ADD COLUMN IF NOT EXISTS "user_agent" VARCHAR(512);
