/** Tizim maydonlari — klient importi modalidagi tartib (jadval bilan mos). */
export const CLIENT_IMPORT_MAPPABLE_FIELDS: { key: string; label: string }[] = [
  { key: "name", label: "Наименование (majburiy)" },
  { key: "legal_name", label: "Юридическое название" },
  { key: "client_code", label: "Ид клиента / код (qisqa)" },
  { key: "client_pinfl", label: "ПИНФЛ" },
  { key: "phone", label: "Телефон" },
  { key: "address", label: "Адрес" },
  { key: "landmark", label: "Ориентир" },
  { key: "inn", label: "ИНН / STIR" },
  { key: "category", label: "Категория клиента (код)" },
  { key: "client_type_code", label: "Тип клиента (код)" },
  { key: "client_format", label: "Формат (код)" },
  { key: "sales_channel", label: "Торговый канал (код)" },
  { key: "region", label: "Область / viloyat" },
  { key: "district", label: "Туман / район" },
  { key: "city", label: "Город / шаҳар" },
  { key: "city_code", label: "Город (код) — hudud bilan moslash" },
  { key: "neighborhood", label: "Махалла" },
  { key: "zone", label: "Зона" },
  { key: "street", label: "Кўча / улица" },
  { key: "house_number", label: "Уй рақами" },
  { key: "apartment", label: "Хонадон" },
  { key: "credit_limit", label: "Kredit limiti" },
  { key: "is_active", label: "Faollik (ha/yoq)" },
  { key: "responsible_person", label: "Mas’ul shaxs" },
  { key: "pdl", label: "P-D-L" },
  { key: "logistics_service", label: "Logistika" },
  { key: "license_until", label: "Litsenziya muddati" },
  { key: "working_hours", label: "Ish vaqti" },
  { key: "gps_text", label: "GPS matni" },
  { key: "latitude", label: "Широта" },
  { key: "longitude", label: "Долгота" },
  { key: "notes", label: "Izoh / prim." },
  { key: "product_category_ref", label: "Mahsulot toifasi (matn / kod)" },
  { key: "contact1_firstName", label: "Kontakt 1: ism" },
  { key: "contact1_lastName", label: "Kontakt 1: familiya" },
  { key: "contact1_phone", label: "Kontakt 1: telefon" },
  { key: "contact2_firstName", label: "Kontakt 2: ism" },
  { key: "contact2_lastName", label: "Kontakt 2: familiya" },
  { key: "contact2_phone", label: "Kontakt 2: telefon" },
  { key: "contact3_firstName", label: "Kontakt 3: ism" },
  { key: "contact3_lastName", label: "Kontakt 3: familiya" },
  { key: "contact3_phone", label: "Kontakt 3: telefon" }
];
